build: cfd-543 check ECR image scan results

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,6 +51,7 @@ jobs:
       - slack/notify:
           event: pass
           template: basic_success_1
+
   trigger-workflows:
     executor: node
     steps:
@@ -163,6 +164,47 @@ jobs:
             cd cypress_tests
             npm ci
             ./node_modules/.bin/tsc
+
+  check-image-scan-results:
+    parameters:
+      repo:
+        type: string
+      tag:
+        type: string
+    docker:
+      - image: amazon/aws-cli
+        entrypoint: bash
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            yum install -y jq
+      - run:
+          name: Check Image Scan Findings
+          command: |
+            aws ecr wait image-scan-complete --repository-name "<< parameters.repo >>" --image-id "imageTag=<< parameters.tag >>"
+            if [ $(echo $?) -eq 0 ]; then
+              FINDINGS=$(aws ecr describe-image-scan-findings --repository-name "<< parameters.repo >>" --image-id "imageTag=<< parameters.tag >>")
+                status=$(echo "${FINDINGS}" | jq -r ".imageScanStatus.status")
+              NUMBER_OF_FINDINGS=$(echo "${FINDINGS}" | jq -r ".imageScanFindings.findings | length")
+              FINDING_SEVERITY_COUNTS=$(echo "${FINDINGS}" | jq -r ".imageScanFindings.findingSeverityCounts")
+
+              CRITICAL=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.CRITICAL')
+              HIGH=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.HIGH')
+              MEDIUM=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.MEDIUM')
+              LOW=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.LOW')
+              INFORMATIONAL=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.INFORMATIONAL')
+              UNDEFINED=$(echo ${FINDING_SEVERITY_COUNTS} | jq '.UNDEFINED')
+
+              if [ ${CRITICAL} != null ] || [ ${HIGH} != null ]; then
+                echo "ECR image contains vulnerabilities at CRITICAL or HIGH level, with a total of ${NUMBER_OF_FINDINGS} found"
+                echo ${FINDING_SEVERITY_COUNTS}
+                exit 1
+              fi
+            else
+              echo "Waiting for scan result timed out!"
+              exit 2
+            fi
 
   # fdbt-netex-output
   deploy-netex-output-resources-to-test:
@@ -777,6 +819,21 @@ workflows:
           context: tfn-fdbt-core
           path: ~/project/repos/fdbt-site
           dockerfile: Dockerfile
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              only:
+                - develop
+                - master
+
+      - check-image-scan-results:
+          <<: *slack-fail-post-step
+          repo: "${SITE_ECR_REPO}"
+          tag: "${CIRCLE_SHA1}"
+          context: tfn-fdbt-core
+          requires:
+            - aws-ecr/build-and-push-image
           filters:
             tags:
               only: /^v.*/
